title: 臺中一中36屆數資班
markdown: kramdown

social-network-links:
 
  instagram: tcfsh_124
  
# How to display the link to your website in the footer
# Remove this if you don't want a link in the footer
# url-pretty: "tcirc.github.io"

# Create a "tags" index page and make tags on each post clickable
link-tags: true

highlighter: rouge

exclude:
  README.md

# plugins:
#   - jekyll-sitemap

# theme: jekyll-theme-slate
